config/routes.rb
Rails.application.routes.draw do
  get 'profile', to: 'pages#profile'
  get 'characters/index'
  get 'characters/:id', to: 'characters#show'
  devise_for :users, except: [:show]
  root to: 'characters#index'

  resources :characters, except: [:destroy] do
    put :favorite, on: :member
  end

  post 'bookings', to: 'bookings#create'
  patch  "bookings/:id", to: "bookings#validate", as: :validate_booking
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :reviews, only: [:create, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_many :reviews
  belongs_to :user
  belongs_to :character

  validates :start_date, :end_date, :character_id, :user_id, presence: true
  validate :end_date_after_start_date

  private

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:end_date, "must be after the start date")
    end
 end
end

app/models/character.rb
class Character < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :reviews, through: :bookings
  has_one_attached :photo
  geocoded_by :address


  def unavailable_dates
    bookings.pluck(:start_date, :end_date).map do |range|
      { from: range[0], to: range[1] }
    end
  end

  validates :name, :description, :price_per_day, :address, presence: true
  validates :name, uniqueness: true
  validates :price_per_day, numericality: { only_integer: true }
  validates :photo, attached: true, unless: :img_url?

  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch::Model
  pg_search_scope :search_by_name,
    against: [ :name ],
    using: {
      tsearch: {
        prefix: true
      }
    }

  def img_url?
    self.image_url.present?
  end

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :character
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  validates :user_review, :rating, presence: true
  validates :rating, inclusion: { in: 1..5 }, numericality: { only_integer: true }
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable, :confirmable

  has_many :characters
  has_many :bookings
  has_many :favorites
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  include Pundit

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    # devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:update, :validate]

  def create
    @booking = Booking.new(booking_params)
    authorize @booking
    @booking.character = Character.find(params[:booking][:character_id])
    @booking.user = current_user
    redirect_to profile_path if @booking.save!
  end

  def update
    @booking.update(booking_params)
    authorize @booking
    redirect_to profile_path
  end

  def validate
    authorize @booking
    @booking.update!(status: params[:value] == 'true')
    redirect_to profile_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :character_id, :status)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]
  before_action :set_character, except: [ :index, :create ]

  def index
    p params
    if params[:search].present?
      @characters = policy_scope(Character).search_by_name(params[:search][:query])
    else
      @characters = policy_scope(Character).order(created_at: :desc)
    end
  end

  def show
    @character = Character.find(params[:id])
    @booking = Booking.new
    @favorite = Favorite.new
    authorize @favorite
    authorize @character
    authorize @booking

    @markers =
      [{
        lat: @character.latitude,
        lng: @character.longitude,
        image_url: helpers.asset_url('mickey.png')
      }]


  end


  def new
    @character = Character.new
  end

  def create
    @character = Character.new(character_params)
    authorize @character
    @character.user = current_user
    if @character.save
      redirect_to profile_path
    else
      redirect_to profile_path
    end
  end

  def edit
  end

  def update
    @character.update(character_params)
    authorize @character
    redirect_to profile_path
  end

  def favorite
    authorize @character
    if params['type'] == "favorite"
      @favorite = Favorite.new(favorite_params)
      @user = current_user.id
      @character = Character.find(params[:id])
      @favorite.user_id = @user
      @favorite.character_id = @character.id
      if @favorite.save
        redirect_to character_path(@character)
      end
    else
      character = Character.find(params[:id])
      favorite = Favorite.where(character_id: character.id, user_id: current_user.id)
      current_user.favorites.delete(favorite)
      redirect_to character_path(@character)
    end
  end

  private

  def character_params
    params.require(:character).permit(:name, :description, :image_url, :address, :price_per_day, :status, :photo)
  end

  def favorite_params
    params.permit(:character_id, :user_id)
  end

  def set_character
    @character = Character.find(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def profile
    @character = Character.new
    @review = Review.new
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @review = Review.new(reviews_params)
    authorize @review
    if @review.save!
      redirect_to profile_path
    else
      redirect_to profile_path
    end
  end


  private

  def reviews_params
    params.require(:review).permit(:user_review, :rating, :booking_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/characters/_info_window.html.erb
<h2><%= character.name %></h2>
<p><%= character.address %></p>

app/views/characters/index.html.erb
<div id="index-view">
  <%= render 'shared/navbar_homepage' %>
  <%= render 'components/banner'%>
  

<div class="container mt-3">
  <div class="row">
    <% @characters.each do |character| %>
      <% if character.status %>
        <div class="col-sm-12 col-md-6 col-lg-4">
          <div class="character-card">
            <%= link_to character_path(character) do %>
               <% if character.image_url.present? %>
                 <div class="flat-card-image" style="background-image: url('<%= character.image_url %>')"></div>
               <% elsif character.photo.attached? %>
                <div><%= cl_image_tag character.photo.key, crop: :fit, class:"flat-card-image" %></div>
               <% end %>
            <% end %>
            <div class="character-card-content">
              <h4><%= character.name %></h4>
              <p><%= character.description %></p>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>
</div>
</div>

app/views/characters/show.html.erb
<%= render 'shared/navbar' %>
<div class="map">
  <div id="map"
    style="width: 100%; height: 600px;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
<div class="container margin-top-negative">
  <div class="row">
    <div class="col-12 col-lg-7">
      <div class="flat-show-card">
        <h1><%= "#{@character.name}" %></h1>
        <% if user_signed_in? %>
          <% if current_user.favorites.where(character_id: @character.id).empty? %>
            <%= link_to favorite_character_path(@character, type: "favorite"), method: :put do %>
              <i class="far fa-star"></i>
            <% end %>
          <% else %>
            <%= link_to favorite_character_path(@character, type: "unfavorite"), method: :put do %>
              <i class="fas fa-star"></i>
            <% end %>
          <% end %>
        <% end %>
      </div>
      <div class="flat-show-card">
        <h3>What we can do together</h3>
        <p><%= @character.description %></p>
        <% if @character.image_url.present? %>
          <div class="map" style="background-image: url('<%= @character.image_url %>')"></div>
        <% elsif @character.photo.attached? %>
          <div><%= cl_image_tag @character.photo.key, crop: :fit, class:"map" %></div>
        <% end %>
      </div>
    </div>
    <div class="col-12 col-lg-5">
      <div class="flat-show-card">
        <div id='character-booking-dates' data-unavailable="<%= @character.unavailable_dates.to_json %>">
          <% if current_user.nil? %>
            <h3>Pick your time to spend with me:</h3>
            <%= simple_form_for(@booking) do |f| %>
              <%= f.input :start_date, as: :string, type: :text %>
              <%= f.input :end_date, as: :string, type: :text %>
              <%= f.input :character_id, :as => :hidden, :input_html => { :value => @character.id } %>
              <%= f.submit "Log in to hire me now", class: "btn btn-primary btn-lg btn-block btn-success" %>
            <% end %>
          <% elsif @character.status && current_user.id != @character.user_id %>
            <h3>Pick your time to spend with me:</h3>
            <%= simple_form_for(@booking) do |f| %>
              <%= f.input :start_date, as: :string, type: :text %>
              <%= f.input :end_date, as: :string, type: :text %>
              <%= f.input :character_id, :as => :hidden, :input_html => { :value => @character.id } %>
              <%= f.submit "Hire me now", class: "btn btn-primary btn-lg btn-block btn-success" %>
            <% end %>
          <% else %>
            <p>Hey <%= current_user.first_name.capitalize %>! This is your character</p>
          <% end %>
        </div>
      </div>
      <div class="flat-show-card">
        <h3>Details</h3>
        <div class="row">
          <div class="col-4">
            <p>Price</p>
          </div>
          <div class="col-8">
            <p><%="#{@character.price_per_day }"%>&euro; per day</p>
          </div>
        </div>
        <div class="row">
          <div class="col-4">
            <p>Host</p>
          </div>
          <div class="col-8">
            <p><%= @character.user.first_name.capitalize %></p>
          </div>
        </div>
      </div>
      <div class="flat-show-card">
        <h3>Reviews</h3>
        <ul class="list-group">
          <% @character.reviews.each do |review| %>
            <li class="list-group-item"><%= review.user_review %></li>
          <% end %>
        </ul>
      </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fantasia</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flatpickr/4.6.6/flatpickr.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
   <h1>Fantasia</h1>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <%= image_tag "https://eu.ui-avatars.com/api/?name=#{current_user.first_name}+#{current_user.last_name}", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Profile", profile_path, class: "dropdown-item" %>
            <%= link_to "Acount Details", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_navbar_homepage.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-homepage">
  <%= link_to root_path, class: "navbar-brand" do %>
   <h1>Fantasia</h1>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <%= image_tag "https://eu.ui-avatars.com/api/?name=#{current_user.first_name}+#{current_user.last_name}", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Profile", profile_path, class: "dropdown-item" %>
            <%= link_to "Acount Details", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>